swagger: "2.0"
info:
  version: 1.0.0 //lascia
  title: "trentose2jan12prova"
  description: Esame di ingegneria del sw2
  termsOfService: http://swagger.io/terms/
  contact:
    name: Enrico Donatoni
    email: enrico.donatoni@studenti.unitn.it
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-prova.herokuapp.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /getArea:
    get:
      description: |
        Calcola area
      operationId: getArea
      parameters:
        - name: side1
          in: query
          description: lato 1
          required: true
          type: integer
        - name: side2
          in: query
          description: lato 2
          required: true
          type: integer
      responses:
        200:
          description: risposta positiva Area
          schema:
            $ref: '#/definitions/getArea'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
definitions:
  getArea:
    allOf:
      - $ref: '#/definitions/getArea'
      - required:
        - side 1
        - side 2
        properties:
          side1:
            type: integer
          side2:
            type: integer
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string